### ISSUE TITLE
Issue determining symptoms and affected body parts: e.g. arms

### ISSUE THREAD

**Issue by rgtlai** [allenai/scispacy#116]
I am trying to determine a way to retrieve symptoms and the affected body parts when a text is analyzed. I am using en_ner_bc5cdr_md and en_ner_bionlp13cg_md to retrieve this information. But I do seem some issues. For example

```
text ="I have numbness in my arm and leg"

import scispacy
import spacy
symptom_nlp = spacy.load("en_ner_bc5cdr_md") 
organ_nlp = spacy.load("en_ner_bionlp13cg_md")


text ="I have numbness in my arm and leg"

doc_symptoms = symptom_nlp(text)
doc_organs = organ_nlp(text)
```

I get the following results:
```
Symptoms:
numbness DISEASE
Organ:
arm CANCER
leg ORGAN
```

I never thought of any correlation between arm and cancer. Also when I just use text = "I have numbness in my arm" , the word arm is not even detected. Also if I change to text = "I have numbness in my arm and leg and toes" I get the following:

```
Symptoms:
numbness DISEASE
Organ:
arm PATHOLOGICAL_FORMATION
leg ORGAN
```

Any ideas why? Any help would be appreciated. Thank you.

I am using
spacy Version: 2.1.3
scispacy Version: 0.2.0

**Comment by danielkingai2** [comment]
Thanks for the issue! Unfortunately, one of the downsides of using a trained model is that it is sometimes wrong. I would have to dig into the data further to see if there might be something weird going on with the annotations for arm or not. 

If there are a small number of specific cases that would be useful to fix for your dataset/task, you may want to check out spaCy's (Entity Ruler)[https://spacy.io/api/entityruler]. This would allow you to write rules for entity identification, for which you could ensure their correctness. You could also potentially try further training the NER model with labeled cases that match the mistakes you see, as described here: https://spacy.io/usage/training#ner. Otherwise, unfortunately mistakes are part of any trained model. You can see this thread on spaCy for their discussion of this topic as well: https://github.com/explosion/spaCy/issues/3052. Thanks again for your interest in this library!

**Comment by rgtlai** [comment]
@danielkingai2, Thank you. Sorry for the late reply.
