### ISSUE TITLE
Archived download link for NER models for version==0.2.3

### ISSUE THREAD

**Issue by masonedmison** [allenai/scispacy#181]
Hi!

Firstly, Thank you for this awesome tool. 

I was wondering if there were archived download links available for the scispacy NER models (craft, jnlpba, etc.) for scispacy version 0.2.3? I have been able to download the core models using pip install <url to AWS server> but receive an error when I try this for the NER models. 

I am still using 0.2.3 because I am using neural  coref which requires spacy 2.1.3 which in turns requires I have an older version of scispacy.

Thanks in advance!

**Comment by danielkingai2** [comment]
You should be able to use the same links from the readme (which look like this https://s3-us-west-2.amazonaws.com/ai2-s2-scispacy/releases/v0.2.4/en_core_sci_sm-0.2.4.tar.gz or this https://s3-us-west-2.amazonaws.com/ai2-s2-scispacy/releases/v0.2.4/en_ner_craft_md-0.2.4.tar.gz), but with each of `0.2.4` replaced with `0.2.3`. So that would be https://s3-us-west-2.amazonaws.com/ai2-s2-scispacy/releases/v0.2.3/en_core_sci_sm-0.2.3.tar.gz or https://s3-us-west-2.amazonaws.com/ai2-s2-scispacy/releases/v0.2.3/en_ner_craft_md-0.2.3.tar.gz for example.

**Comment by masonedmison** [comment]
Excellent that indeed works! I must have flubbed the url the first time around - sorry about that. 
In terms of loading the NER models, do I add model to the SpaCY pipeline, 
e.g. `nlp.add_pipe('en-ner-craft-md')`?

**Comment by danielkingai2** [comment]
The NER models are there own separate models (they are just the NER pipe trained on top of `en_core_sci_md`), so you would use them the same as the others, `nlp=spacy.load('en_ner_craft_md')`. If you need to combine the output from multiple NER models , we don't currently have a good way to do that, and the suggested way would be to run both models separately and then combine the output however you choose to.

**Comment by masonedmison** [comment]
Awesome - everything works as expected. Thank you!
