### ISSUE TITLE
Entities covered in en_core_sci_sm model

### ISSUE THREAD

**Issue by rshah1990** [allenai/scispacy#206]
Hi Team,

We are using NER of **en_core_sci_sm**  model it is identifying the entity but does not give entity type (_label gives only entity as an output).  Can you please share list of entity covered in the model & how can we re-train that model to improve performance.

**Comment by DeNeutoy** [comment]
Hi @rshah1990,

The mention detector is trained on med mentions:
https://github.com/chanzuckerberg/MedMentions

which is really a dataset for entity linking. Because of this, the NER model is quite generic (it identifies a lot of mentions) and so we don't provide the types. You could train a model to predict the types though, if that was helpful.
