### ISSUE TITLE
Divergent NER results whether there is a parser or not. 

### ISSUE THREAD

**Issue by EmilieDel** [allenai/scispacy#260]
Hello, 

After fine-tuning a scispacy NER model (`en_ner_bc5cdr_md`) on the entity type **DISEASE**, it seems like the NER results are different whether the parser is enabled or not. All experiments are done with spacy v2.3.1 and scispacy v0.2.4
![image](https://user-images.githubusercontent.com/47669575/89894189-fa2f2000-dbd9-11ea-8ae5-c3dceabc16aa.png)
As you can see on the picture above:
- If the parser is enabled, 4 entities are detected.
- If the parser is disabled, 3 entities are detected (one of which is very long and actually contains 2 of the previous entities). 

However, here is a part of the [spaCy documentation ](https://spacy.io/usage/processing-pipelines)
_In spaCy v2.x, the statistical components like the tagger or parser are independent and don’t share any data between themselves. For example, the named entity recognizer doesn’t use any features set by the tagger and parser, and so on. This means that you can swap them, or remove single components from the pipeline without affecting the others._

Is it also something we can assume for ScispaCy models ? Do you have an idea why the results are different ?

Thanks a lot for your help,

**Comment by danielkingai2** [comment]
So, scispacy v0.2.4 shouldn't actually be compatible with v2.3.1. Could you update to scispacy v0.2.5 just to make sure its not something about versions? I've never seen this before and can't reproduce on the latest versions.

**Comment by EmilieDel** [comment]
Thanks a lot for your reply! I did not know about this incompatibility. Unfortunately, I have the same issue with scispacy v0.2.5 and spacy v2.3.1.

**Comment by danielkingai2** [comment]
Do you have this problem with the raw scispacy model (en_ner_bc5cdr_md)?

**Comment by DeNeutoy** [comment]
I think this behaviour might be expected, because the NER model will run at the sentence level (i.e entities which cross sentence boundaries would not be allowed) - if the parser is not set, there will be no sentences in the doc and so the NER model will run on the full input, which looks like it has confused your fine tuned NER model here.

Are the entities you are fine tuning it on very long? Generally this is not recommended and you should try a different approach, such as text classification.
