### ISSUE TITLE
How to Improve Model Performance?

### ISSUE THREAD

**Issue by predestination** [allenai/scispacy#279]
Hi SciSpacy Team,
First I want to thank the team for this wonderful library.

Given a sentence, I am trying to extract **"Disease"** & **"Treatment"** related entities from the sentence.
**Eg:**  Patient is suffering from cancer and is undergoing chemotherapy.
**Output Expected** : **Disease :** cancer , **Treatment :** chemotherapy 

So Initially I started with specialized NER ( **en_ner_bc5cdr_md**) just to extract the disease-related entities. It was giving good results but not giving all the disease-related entities.
**Eg:**  patient was not able to attend work due to influenza
For the above example, it's not returning **influenza**. Like this, there are many examples like "flu" and many others.

As a next step, I moved to **en_core_sci_lg**  which is actually giving all the medical-related entities from the text. But, the problem was, it doesn't classify the entity into categories ( like disease, treatment).
When I explored further, I understood that I can take the help of UMLS integration, where for each entity returned by the en_core_sci_lg, we can extract the umls_ent using entity._.umls_ents and then get it's **concept name, concept id, type** and even threshold score.

Here I am using **type**, and by using **type codes** from **UMLS_Semantic_Type_Tree**, I am trying to classify the entity into either Disease or treatment. Problem is,  I'm getting false positives by using this approach and also sometimes I am missing the entities too.

Please find the disease, treatment codes, and also other things which I am using in my code.

**disease_codes** : T041, T047, T048, T184, T191, T005
**treatment_codes** : T091, T061, T060, T059
**linker_lg = UmlsEntityLinker(k=5)** and also tried **max_entities_per_mention** parameter with different values.

Please find some of the **False Positives** below:
**Disease:** push pull, drive, global delay, decision, reasoning e.t.c
**Treatment:** medication delivery, hygiene, elevation, counseling group e.t.c

So, what else I can do to improve the results?

Will training model on my own data, helps here? or do we have a better approach?

Also Just want to add, sometimes the sentences which I have, won't follow any grammar and there can be spelling mistakes too. 
It can be as worse as 
" patient hdache nt sleepng well "

Thanks

**Comment by DeNeutoy** [comment]
Hi @predestination,

Thanks for the comprehensive description of what you are trying to do. Broadly this seems like a good approach. Also, there is an element of non-determinism in using statistical models, so they are never going to be perfect. However, there are a couple of things you might want to try:

 - https://github.com/allenai/scispacy#entitylinker Currently you are using the UMLS entity linker. You might want to try either the MESH or HPO linkers, as these are less noisy (because they have fewer concepts and are more tightly controlled).

- The data the entity linker was trained on contains verbs which can be linked. In your case, diseases and treatments are very unlikely to be verbs, so I would suggest filtering them out. 

- Finally, you might try to filter the entities you extract based on some sentence level keywords. E.g if "treated" or "patient" is in the sentence, you can be a little more aggressive in your extractions, perhaps expanding to noun phrases etc.

Hopefully these ideas will give your method a boost!

**Comment by predestination** [comment]
Thank you for the suggestions. I will start with MESH, HPO linkers.

- When you mentioned, "The data the entity linker was trained on contains verbs which can be linked. ",  are you talking about the entity linkers MESH & HPO or else all the entity linkers that are present?

- https://spacy.io/usage/training Also, what are your thoughts on training a model on the data I have using Spacy?

**Comment by DeNeutoy** [comment]
Hi @predestination,

Yes all the entity linkers use a mention detection NER model which was trained on the Med Mentions corpus, which is a general entity linking dataset for biomed. 

It might be worthwhile to train a new model, it depends a little bit on the resources that you have available, as it can take a while to collect good data etc.

You might also be interested in these spacy models:

https://github.com/NLPatVCU/medaCy

https://github.com/kormilitzin/med7

which are more for drug and dosage information. It might give you some idea of how to create your own, or perhaps they are useful directly.

**Comment by predestination** [comment]
Thank you for the suggestions. 

For my use case as of now, we are not extracting anything related to Drugs, but in future if it's the case, I will definitely try it out.
