### ISSUE TITLE
8X runtime increase with EntityLinker

### ISSUE THREAD

**Issue by JohnGiorgi** [allenai/scispacy#284]
This is less of an issue and more of a question.

We were hoping to use the EntityLinker pipe on some clinical notes. We have tens of thousands of them, each with an average of 1100 tokens. We find that running the EntityLinker on these notes is prohibitively expensive in terms of runtime and memory. This is the case even when we select a subset of a few thousand.

In a dumb little benchmark I put together [here](https://colab.research.google.com/drive/10pSZJkQr3IFg_g40vV-6fvMYgcCBqJ5R?usp=sharing) on the 20-newsgroup dataset, I found that adding the EntityLinker pipe increases the runtime of scispacy by ~8X(!) when using `nlp.pipe()`:

![image](https://user-images.githubusercontent.com/8917831/97205920-76bfac80-178e-11eb-8524-5dce07e99bb5.png)

Is this expected? Are there any tips/tricks for getting it to run in a reasonable amount of time when you have lots of texts? I have already disabled the components I don't need (`"tagger"`, `"parser"`) and am using `nlp.pipe()` as recommended in the spacy documentation.

**Comment by DeNeutoy** [comment]
Hi @JohnGiorgi ,


This is caused by a couple of things:

1. In your colab, the instance is not installing the right nmslib package. The entity linker uses nmslib, an approximate nearest neighbour library to do sparse nearest neighbour search over tf-idf vectors for entities. I don't entirely understand why but colab is not installing a version of nmslib which is compiled to use the features of the CPU that the colab clearly has. If you look in the colab logs, you will see this:

`Your CPU supports instructions that this binary was not compiled to use: SSE3 SSE4.1 SSE4.2 AVX AVX2`

When I run that benchmark on my macbook, I get a 2x (3.1s) slowdown from using the linker, not an 8x slowdown, but it is correctly using all the instruction sets apart from AVX2.

2. The Entity linker does unfortunately use a lot of memory, because of the search.

3. UMLS is an extremely big KB - 2.3M concepts. We have other ones which are much, much smaller, and higher precision. E.g the `mesh` linker only has around 30k entities and is much cleaner. Using MESH, the runtime (without changing the EFS paramter, see below) is 2.41s.

4. The Candidate Generator which the entity linker uses has a parameter which controls the speed/precision trade off for the approximate nearest neighbours search (the numbers here are measuring ANN queries per second).

![image](https://user-images.githubusercontent.com/16001974/97484674-4acf3300-1916-11eb-924e-12941df0fd6e.png)


By default, we set this parameter to `200`. You can change this value to speed up the search substantially, for a small ish cost in recall:

https://github.com/allenai/scispacy/blob/master/scispacy/candidate_generation.py#L204

Let me know if that's helpful!

**Comment by JohnGiorgi** [comment]
@DeNeutoy 

Thanks so much for the detailed response. This is very helpful. 

I will avoid colab for now and try out the mesh linker with a tuned `ef_search`!
