### ISSUE TITLE
Filtering Entity Linking candidates based on sentence similarity

### ISSUE THREAD

**Issue by vasudev13** [allenai/scispacy#352]
Hi, thanks for developing such an awesome library. I wanted to know if there is way to generate candidates based on the context information. In certain cases, the distance seems to be same for all possible candidates where the context may help describing the nearest candidate. For Example-

```

for x in nlp("date of birth: sex: male service: micu and then ...").ents[1]._.kb_ents:
    print(linker.kb.cui_to_entity[x[0]],x[1],sep="\n\n\n")
    print()
```

Gives output:

```
CUI: C0009253, Name: Coitus
Definition: The sexual union of a male and a female, a term used for human only.
TUI(s): T040
Aliases (abbreviated, total: 21): 
	 vaginal intercourse, Sexual act, NOS, SEXUAL INTERCOURSE, Intercourse (observable entity), making love, Sex, sexual act, sexual intercourse, Coitus, NOS, coitus


0.9999999403953552

CUI: C0036864, Name: Sex Behavior
Definition: Sexual activities of humans.
TUI(s): T053
Aliases (abbreviated, total: 29): 
	 sexual behaviour, sexual behaviors, Sexual behavior, Sexual Behavior, sex behavior, sexuality, Sexually, Activity, Sexual, Sex, Sexual behaviour, NOS


0.9999999403953552

CUI: C0079399, Name: Gender
Definition: Socially-constructed identity of male or female.
TUI(s): T032
Aliases: (total: 7): 
	 gender, Gender, individual sex, sex (gender), gendered, Gender (observable entity), sex


0.9999999403953552

CUI: C1314687, Name: Sexual intercourse - finding
Definition: None
TUI(s): T033
Aliases (abbreviated, total: 12): 
	 Sexual act, Biological sex (property), Biological sex, Coitus, Finding of sexual intercourse (finding), Sexual intercourse - finding, Finding of sexual intercourse, Sex, Vaginal intercourse, SI - Sexual intercourse


0.9999999403953552

CUI: C1418662, Name: PLXNA3 gene
Definition: None
TUI(s): T028
Aliases (abbreviated, total: 11): 
	 XAP-6, Plxn3, PLXN4, PLXNA3, plexin A3, SEX, 6.3, TRANSMEMBRANE PROTEIN SEX, PLXNA3 gene, PLEXIN 4


0.9999999403953552


```
One possible way I thought of was to make use of concept definitions. Would be great if you could share your inputs on this!

Thanks in Advance!

Vasu

**Comment by danielkingai2** [comment]
This is definitely a limitation of the current approach and we would love to have a more robust entity linker that does exactly what you describe. Take in the context of the text and the definition (and maybe type and aliases) of the candidate entities and predict which one is correct. I don't know if a simple sentence similarity would be enough or not, but is something you could evaluate on the medmentions dataset, which is how we evaluated the current entity linker. 

The distance is the same for all of these because they all have an alias that is exactly `sex`.
