### ISSUE TITLE
Word Embedding Implementation

### ISSUE THREAD

**Issue by chen-yifu** [allenai/scispacy#353]
Hi,

Thanks for this post.

Does the "doc.similarity(...)" function use the word vector from Spacy (which is not specifically trained on biomedical text at all)?

In other words, is there any difference between calling "doc.similarity(...)" via Spacy or SciSpacy?

Thanks a lot for your attention,
Yifu

**Comment by MichalMalyska** [comment]
This will depend on the model you use - I think models like "en-core-sci-lg" will have been trained on biomedical texts

**Comment by chen-yifu** [comment]
Hi @MichalMalyska , 
Thank you for responding. I'm sorry I wasn't able to find the corresponding section on your paper. Would you please let me know if the embedding model is described anywhere?
Thanks again,
Yifu

**Comment by MichalMalyska** [comment]
Hey, 

In the descriptions for all their vocabs they have:

"scispaCy models are trained on data from a variety of sources. In particular, we use:

    The GENIA 1.0 Treebank, converted to basic Universal Dependencies using the Stanford Dependency Converter. We have made this dataset available along with the original raw data.
    word2vec word vectors trained on the Pubmed Central Open Access Subset.
    The MedMentions Entity Linking dataset, used for training a mention detector.
    Ontonotes 5.0 to make the parser and tagger more robust to non-biomedical text. Unfortunately this is not publically available.
"

To me, this means that all of the language models listed on https://allenai.github.io/scispacy/ should be trained on these datasets and the word embeddings should be tailored to biomedical texts (with some robustness to non-biomed text via Ontonotes)

btw, I am not part of allenai - I just use the libraries and try to be moderately helpful in the issues on GH

**Comment by danielkingai2** [comment]
Thanks @MichalMalyska, everything you said is correct, and I'll add some more details. Here is an example:
```
In [1]: import spacy

In [2]: sci_sm = spacy.load('en_core_sci_sm')

In [3]: sci_md = spacy.load('en_core_sci_md')

In [4]: web_sm = spacy.load('en_core_web_sm')

In [5]: web_md = spacy.load('en_core_web_md')

In [6]: text1 = "Tylenol is used to treat headaches"

In [7]: text2 = "Ibuprofen is used to alleviate migraines"

In [8]: sci_sm(text1).similarity(sci_sm(text2))
/net/nfs2.corp/s2-research/daniel/miniconda3/envs/scispacy_3_released/bin/ipython:1: UserWarning: [W007] The model you're using has no word vectors loaded, so the result of the Doc.similarity method will be based on the tagger, parser and NER, which may not give useful similarity judgements. This may happen if you're using one of the small models, e.g. `en_core_web_sm`, which don't ship with word vectors and only use context-sensitive tensors. You can always add your own word vectors, or use one of the larger models instead if available.
  #!/net/nfs2.corp/s2-research/daniel/miniconda3/envs/scispacy_3_released/bin/python
Out[8]: 0.8506796430737505

In [9]: sci_md(text1).similarity(sci_md(text2))
Out[9]: 0.8859446651287843

In [10]: web_sm(text1).similarity(web_sm(text2))
/net/nfs2.corp/s2-research/daniel/miniconda3/envs/scispacy_3_released/bin/ipython:1: UserWarning: [W007] The model you're using has no word vectors loaded, so the result of the Doc.similarity method will be based on the tagger, parser and NER, which may not give useful similarity judgements. This may happen if you're using one of the small models, e.g. `en_core_web_sm`, which don't ship with word vectors and only use context-sensitive tensors. You can always add your own word vectors, or use one of the larger models instead if available.
  #!/net/nfs2.corp/s2-research/daniel/miniconda3/envs/scispacy_3_released/bin/python
Out[10]: 0.8650837072546965

In [11]: web_md(text1).similarity(web_md(text2))
Out[11]: 0.9257868773729903

In [12]: sci_md("tylenol").similarity(sci_md("ibuprofen"))
Out[12]: 0.821704759629651

In [13]: web_md("tylenol").similarity(web_md("ibuprofen"))
Out[13]: 0.6202061460191125
```

Neither the scispacy small model nor the spacy small model have word vectors, so they compute similarity based on the tagger, parser, and NER, as the warning message says. This will be different between spacy and scispacy, because the parser, tagger, and NER are trained on biomedical data in scispacy.

For the medium and large models, the spacy vectors are trained on Ontonotes (general domain web data), and the scispacy vectors are trained on pubmed papers (academic, biomedical data). So there will also be a difference for these models. Which to use probably depends on your use case, and I haven't played with the similarity function much myself, but my example shows about how I would expect it to go. That is, "tylenol" and "ibuprofen" are more similar according to scispacy vectors than spacy vectors, but the full sentence is scored to be more similar by spacy than scispacy, maybe because the spacy vectors are better at similarity of "normal" text. This part is mostly I guess, but I hope that answers your question!

**Comment by chen-yifu** [comment]
Hi Daniel, 
Thank you for posting the detailed explanation. Would you please let me know how the embeddings are constructed? Specifically, I wonder if the embeddings are generated from neural networks?
Thanks so much again.
