### ISSUE TITLE
Is there any difference between the returned entities with the same score?

### ISSUE THREAD

**Issue by amirj** [allenai/scispacy#358]
I just noticed that if I shuffle the returned entities by UMLS entity linker and then choose the max score, the performance will be significantly decreased based on MedMentions dataset. 

I've been thinking if you're considering any constraints/rules/... when ordering the entities with equally high score?

For example, "22q11.2 Deletion Syndrome" being mapped to [**('C0012236', 1.0), ('C0220704', 1.0), ('C1321551', 1.0)**, ('C4518343', 0.8799166679382324), ('C2936346', 0.8731739521026611)], I just noticed that in most cases the first item is more relevant than others with equal score.

**Comment by MichalMalyska** [comment]
As far as I understand the Entity Linking + Candidate Generation, the reason this happens is probably that:
1. all of these entities have the same alias (hence the equal scores)
2. the candidate generator doesn't care about aliases at first, so the order returned will be based on the sparse 3-char TF-IDF cosine similarity. 

So I think these are sorted by score and within score by the cosine sim using their candidate generation (or rather they come in that order and since the scores are the same they don't get moved around).

**Comment by danielkingai2** [comment]
The canonical name and aliases should all be treated the same. The candidates are initially sorted by concept id (https://github.com/allenai/scispacy/blob/2290a80cfe0948e48d8ecfbd60064019d57a6874/scispacy/candidate_generation.py#L354), and then by score (https://github.com/allenai/scispacy/blob/2290a80cfe0948e48d8ecfbd60064019d57a6874/scispacy/linking.py#L127). Although when we evaluated this, the line sorting by concept id was not there, and they were just taken in whatever order the approximate nearest neighbors returned them in. It'd be pretty weird if sorting by concept id helped on medmentions somehow...

**Comment by MichalMalyska** [comment]
It looks like that change was added ~4 months ago, so if this is ran under the 0.3.0 release this would make sense

**Comment by amirj** [comment]
Thanks for clarification @danielkingai2
