### ISSUE TITLE
RuntimeError running sentence with many backslashes

### ISSUE THREAD

**Issue by juhai** [allenai/scispacy#375]
The following reproduces the error:
``` python
import spacy
scispacy = spacy.load('en_core_sci_scibert')
scispacy(''.join(['\\'] * 511 )))
```
using scispacy==0.4.0

Error message: `RuntimeError: The size of tensor a (513) must match the size of tensor b (512) at non-singleton dimension 1`
If I reduce `511` to a lower number in the call, it works. In my case, this is not the real input but my data sometimes contains equations that use LaTeX syntax and have a lot of backslashed items.

This error does not occur with Spacy's own `en_core_web_trf` model.

**Comment by juhai** [comment]
A similar issue reported on Spacy too https://github.com/explosion/spaCy/issues/7891

**Comment by danielkingai2** [comment]
hmm, it looks like this is a spacy internal issue, so I will leave it to them. An off the cuff guess is that something in spacy-transformers assumes that each token is less than 512 characters without checking. if it is not too hard, you could try preprocessing your data to make sure those really long tokens don't exist (just throw some space in the middle, or remove them, because it is pretty unlikely that spacy/scispacy are going to do anything reasonable with some long latex string)

**Comment by juhai** [comment]
Thanks, the real data isn't this bad. The backslashes seem to cause the problem as long as there are enough of them, but not necessarily in a single sequence. I am filtering the sentences with equations from the data and everything looks good. Thanks for the quick response.
