### ISSUE TITLE
Multiple linkers in pipeline

### ISSUE THREAD

**Issue by ddomingof** [allenai/scispacy#378]
Hi, I would like to add multiple linkers (e.g., umls and mesh) to the pipeline and spacy is complaining since they have the same name. Is this even possible?

```python
nlp.add_pipe(
      'scispacy_linker',
      config={
          'linker_name': 'umls',
      },
  )
  
nlp.add_pipe(
      'scispacy_linker',
      config={
          'linker_name': 'mesh',
      },
  )
```
Thanks!

**Comment by MichalMalyska** [comment]
I don't think this will work as the linkers would just be overwriting properties, so even if you did have 2 in a pipeline, the resulting ent._.kb_ents would only come from the last one you call. 

The way to hack around it would be to add the possibility of passing the extension name (instead of kb_ents it could be like mash_ents and umls_ents) when you instantiate the linker

**Comment by danielkingai2** [comment]
^This is correct. I would suggest instantiating the linkers separately, and running them in a loop and then doing whatever you want with the output. something like
```
doc = nlp_without_linker(text)
for linker in linker:
    linked_doc = linker(doc)
    # save/clear whatever doc state you want
```

**Comment by ddomingof** [comment]
Thanks a lot guys, I think I will simply use two different models loaded with the different linkers
