### ISSUE TITLE
Entity Linker - documentation issues and questions

### ISSUE THREAD

**Issue by ldorigo** [allenai/scispacy#394]
Hello,

I am experimenting with the entity linkers and I have a couple of questions/comments. If you prefer I can make separate issues for each of them but I think it's clearer to have a single issue.

First small question: Is the documentation for the linkers and candidate generators outdated? The docstring for CandidateGenerator says

>      A candidate generator for entity linking to a KnowledgeBase. Currently, two defaults are available:
>      - Unified Medical Language System (UMLS).
>      - Medical Subject Headings (MESH)

But the readme lists a few other ontologies as well (and they do seem to be handled in the code)

Second higher level question:  I'm interested in your reasons for using specifically 3-gram tf-idf vectorization for ANN for candidate generation? Did you publish a paper or something I could read?  I would like to experiment with using pre-trained word embeddings instead, but it seems like a rather obvious idea, so I'm curious if there are reasons you didn't do that in the first place?

Related to that, if I wanted to generate an index based on word embeddings - how expensive is the generation of the ANN index? I only have limited computing capabilities available, and the default value for the number of threads in https://github.com/allenai/scispacy/blob/3d153ddad1f11f000f961f7a92c0d862b93c0973/scispacy/candidate_generation.py#L396

>    num_threads = 60  # set based on the machine

Worries me a little. I don't want to spend a lot of time preparing this only to find out that the training is way too expensive to be done in a reasonable time.

Thanks in advance!

**Comment by danielkingai2** [comment]
1. Yes, this documentation is out of date, thank you!
2. We do have a paper, although it may or may not answer your question (https://www.semanticscholar.org/paper/ScispaCy%3A-Fast-and-Robust-Models-for-Biomedical-Neumann-King/de28ec1d7bd38c8fc4e8ac59b6133800818b4e29). Figure 3 shows the recall curve as we increase the number of candidates with our candidate generator. We did not dive into what remains in that last bit of recall and whether word embeddings could help. The paper we compare against (https://aclanthology.org/P18-1010.pdf) uses a different string similarity measure for the candidate generation. Character trigram similarity is a pretty common string similarity measure, which is why we choose to use it. The intention is really that a further entity linker that takes into account the context of the mention rather than just the mention string itself should be used. If I were going to experiment, I would probably start by experimenting with reranking the candidates we generate to increase precision, rather than improving the candidate generator to increase recall.
3. Sorry, I don't really remember the compute profile of creating the index. We use nmslib (https://github.com/nmslib/nmslib) though, so you might be able to find some more information there.

**Comment by MichalMalyska** [comment]
I have trained a couple of my own versions of linkers and plugged into scispacy:

2) the 3-char works surprisingly well, with one exception (on my usecases), because "ing" is 3 chars, it makes quite a significant difference between "bleed" and "bleeding" etc. 

3) I created an index on an i7 processor for an ontology with the size of ~120k, and it took ~1h total, so for larger ontologies (especially if you decide to go with word vectors which are not sparse) you definitely need something beefier.
