### ISSUE TITLE
HTTPSCOnnectionPool for s3=us-west-2.amazonaws.com

### ISSUE THREAD

**Issue by HodaMemar** [allenai/scispacy#430]
Hello
Thank you for this helpful library
I have a problem with :

**https://s3-us-west-2.amazonaws.com/ai2-s2-scispacy/releases/v0.5.0/en_ner_bc5cdr_md-0.5.0.tar.gz**

I can install it on colab
but when I try to install it on my pc i get an error : 

**upload failed: ./icon.jpg to s3://mybucket/myfolder/icon.jpg HTTPSConnectionPool(host='s3-us-west-1b.amazonaws.com', port=443): Max retries exceeded with url: /mybucket/myfolder/icon.jpg (Caused by : [Errno -2] Name or service not known)**

Other available zones such as ap-south-1a and ap-south-1b are not working on my pc.
Could you please help me in this issue?
Thank you

**Comment by DeNeutoy** [comment]
Hi @HodaMemar ,

It looks like you are trying to upload something? Our bucket is read only, so that won't work.

You should just be able to do `pip install <model url>` rather than having to explicitly download the package with the aws cli.

If those don't help, please post the full error as well as the command you ran.
