### ISSUE TITLE
Difficulty installing nmslib

### ISSUE THREAD

**Issue by GBULLR** [allenai/scispacy#470]
Windows 10
pip install scispacy fails: nmslib  issue after installing c++ tools and all the stuff. 
Downloading from github also fails
python setup.py install: install fails 
python setup.py build: build fails 

Can you all please look into this. I may be terrible at setting up modules and environments, but several hours trying to install a module is unacceptable. Thank you.

I've look on stack-overflow etc. 

Thank you.

**Comment by dakinggg** [comment]
Hi @GBULLR, installing nmslib (https://github.com/nmslib/nmslib) has become difficult over the years. I no longer have a Windows 10 set up to attempt installation on. 

The issue is nmslib install. There are many issues on scispacy related to this, with some possible workarounds (https://github.com/allenai/scispacy/issues/455, https://github.com/allenai/scispacy/issues/446, https://github.com/allenai/scispacy/issues/445, https://github.com/allenai/scispacy/issues/431, https://github.com/allenai/scispacy/issues/426, https://github.com/allenai/scispacy/issues/412, https://github.com/nmslib/nmslib/issues/399, https://github.com/allenai/scispacy/issues/372, https://github.com/allenai/scispacy/issues/291, https://github.com/allenai/scispacy/issues/137, https://github.com/allenai/scispacy/issues/130). It is very system dependent what may work. 

The easiest thing to try is probably to use python 3.9, which nmslib should have prebuilt binaries for.
