### ISSUE TITLE
Model download URLs

### ISSUE THREAD

**Issue by Abhijit-2592** [allenai/scispacy#68]
Hi, Where can I download the trained models? I am unable to find the download URLs for the available models mentioned in this repo.

Moreover the current pip install fails. We have to clone the repo and build from the setup.py files

**Comment by DeNeutoy** [comment]
Hi! Thanks for your interest in the project. We have not released scispacy yet, because we are waiting for the spacy 2.1 release, which should be in a few weeks. I would not recommend trying to use this repository before we release it publicly. Hopefully the release will happen in < 2 weeks and will be accompanied by a full set of models and a technical report.

Watch this space!

**Comment by Abhijit-2592** [comment]
@DeNeutoy thanks for your reply. Is it at all possible to get access to a pre release or alpha version of the models? This project is really amazing and looks promising!

**Comment by DeNeutoy** [comment]
@Abhijit-2592 Thanks for your patience! The models and initial release are ready. 

https://allenai.github.io/scispacy/

```
pip install scispacy
```
