### ISSUE TITLE
Support for spacy-nightly (2.1.0a*) version

### ISSUE THREAD

**Issue by Abhijit-2592** [allenai/scispacy#73]
Looks like the support has changed from spacy-nightly version to spacy 2.0.8. Is it possible to use it with spacy-nightly (2.1.0a*) versions?

**Comment by DeNeutoy** [comment]
Hi! Yes, unfortunately we had to roll back the spacy version, because there was a bug in the spacy nightly release which catastrophically affected the NER models (which hopefully has now been fixed, but I noticed some github issues concerning a later release that made me think there might still be issues). We'll definitely be releasing models once spacy 2.1 is released.

**Comment by Abhijit-2592** [comment]
@DeNeutoy Thanks for the quick response

**Comment by Bharat123rox** [comment]
@DeNeutoy now that spaCy 2.1 is released, could you please provide support for the same?

**Comment by dkarmon** [comment]
@DeNeutoy, thanks for your great work!
When do you expect to release a compatible version for the sciSpacy models with spaCy 2.1?

**Comment by DeNeutoy** [comment]
@dkarmon We will have a new release within 2 weeks which will support spacy 2.1. There will also be a follow-up release with a (rudimentary) entity linker which will link to a subset of UMLS.

**Comment by danielkingai2** [comment]
Version `0.2.0` of `scispacy` is now up, and supports version `2.1.3` of `spacy.
