### ISSUE TITLE
Span.vector usage

### ISSUE THREAD

**Issue by olivomao** [allenai/scispacy#84]
Hi,

I am trying to use en_ner_craft_md and en_ner_jnlpba_md modules.

I found Spacy's Span object has Span.vector as a vector representation its text,
is it possible to use these representations directly for some gene name normalization task (e.g. "Basic Helix-Loop-Helix Transcription Factor Scleraxis" is similar to "SCX" gene)?

Thanks!

Shunfu

**Comment by danielkingai2** [comment]
Empirically, that example does not work (see below). More generally, it will likely be a case by case basis, because it depends on whether or not the training data has enough examples of both of those phrases in similar contexts to understand that they refer to similar things. See #83 for more detail about the word vectors. Of course, you could also use the vectors and/or the similarity of the vectors as an input to another normalization model.

```
>>> import spacy
>>> nlp = spacy.load('en_ner_craft_md')
>>> doc1 = nlp("Basic Helix-Loop-Helix Transcription Factor Scleraxis")
>>> doc2 = nlp("SCX")
>>> doc2.similarity(doc1)
0.0904146602497725
```

**Comment by olivomao** [comment]
I see. Thanks!
